const translation = {
  this_is_a_test_phrase: 'this is only a test phrase',
  msg_logout: 'Logout',
  msg_login: 'Login',
  msg_signup: 'Sign Up',
  msg_signIn_login: 'Sign in or create an account.',
  msg_Create_account: 'Create an account.',
  msg_username: 'Username',
  msg_password: 'Password',
  msg_confirm_password: 'Confirm Password',
  msg_email: 'Email',
  msg_first_name: 'First Name',
  msg_last_name: 'Last Name',
  msg_submit: 'Submit',
  msg_cancel: 'Cancel',
  msg_edit: 'Edit',
  msg_delete: 'Delete',
  msg_user_list: 'User List',
  msg_user_details: 'User Details',
  msg_user_id: 'User ID',
  msg_user_name: 'User Name',
  msg_user_email: 'User Email',
  msg_user_first_name: 'User First Name',
  msg_user_last_name: 'User Last Name',
  msg_user_password: 'User Password',
  msg_user_confirm_password: 'User Confirm Password',
  msg_home: 'Home',
  msg_news: 'News',
  msg_users: 'Users',
  msg_members: 'Members',
  msg_about: 'About Us',
  msg_contact: 'Contact',
  msg_merchandise: 'Merchandise',
  msg_media: 'Media',
  msg_links: 'Links',
  msg_events: 'Events',
  msg_cart: 'Cart',
  msg_checkout: 'Checkout',
  msg_search: 'Search',
  msg_search_placeholder: 'Search...',
  msg_search_results: 'Search Results',
  msg_search_no_results: 'No results found',
  msg_search_no_results_for: 'No results found for',
  msg_search_no_results_for_query: 'No results found for query',
  msg_upcoming_events: 'Upcoming Events',
  msg_past_events: 'Past Events',
  msg_event_details: 'Event Details',
  msg_event_id: 'Event ID',
  msg_event_name: 'Event Name',
  msg_event_date: 'Event Date',
  msg_event_time: 'Event Time',
  msg_event_location: 'Event Location',
  msg_event_description: 'Event Description',
  msg_blog: 'Blog',
  msg_blog_post: 'Blog Post',
  msg_blog_post_id: 'Blog Post ID',
  msg_blog_post_title: 'Blog Post Title',
  msg_blog_post_date: 'Blog Post Date',
  msg_blog_post_time: 'Blog Post Time',
  msg_blog_post_author: 'Blog Post Author',
  msg_blog_post_author_id: 'Blog Post Author ID',
  msg_blog_post_author_name: 'Blog Post Author Name',
  msg_blog_post_author_email: 'Blog Post Author Email',
  msg_blog_post_author_first_name: 'Blog Post Author First Name',
  msg_blog_post_author_last_name: 'Blog Post Author Last Name',
  msg_blog_post_author_image: 'Blog Post Author Image',
  msg_blog_post_author_image_alt: 'Blog Post Author Image Alt',
  msg_blog_post_author_image_caption: 'Blog Post Author Image Caption',
  msg_blog_post_author_image_credit: 'Blog Post Author Image Credit',
  msg_blog_post_author_image_url: 'Blog Post Author Image URL',
  msg_blog_post_author_image_url_alt: 'Blog Post Author Image URL Alt',
  msg_blog_post_content: 'Blog Post Content',
  msg_blog_post_content_html: 'Blog Post Content HTML',
  msg_news_post: 'News Post',
  msg_news_post_id: 'News Post ID',
  msg_news_post_title: 'News Post Title',
  msg_news_post_date: 'News Post Date',


};

export default translation;
